### ISSUE TITLE
Oppia website not accessible

### ISSUE THREAD

**Issue by Stardlight** [oppia/lessons-team#1184] opened 2024-03-09 16:56 UTC
The website has has been inaccessible for some days now on IOS and chrome browser, I tried changing my network provider and also switching to a higher network band and the issue still persists. 
Though it opened at some point and didn't last up to 2mins

**Comment by Hasoye** [comment] 2024-03-10 08:06
Hello @Stardlight try to select ‘do not send these emails’ and see if it works

**Comment by Stardlight** [comment] 2024-03-10 08:07
> Hello @Stardlight try to select ‘do not send these emails’ and see if it works

@Hasoye that's a different thing entirely 
I solved the issue you're talking about

**Comment by Hasoye** [comment] 2024-03-10 08:10
Alright👍

**Comment by IreneAnyadu** [comment] 2024-03-10 12:52
Hello @Stardlight 
I'm still having the same issue. Today will make it the 4th day. Don't know how to rectify this

**Comment by Stardlight** [comment] 2024-03-10 13:09
> Hello @Stardlight 
> I'm still having the same issue. Today will make it the 4th day. Don't know how to rectify this

@IreneAnyadu kindly tag our mentors so their attention can be called to this

**Comment by IreneAnyadu** [comment] 2024-03-10 13:11
> > Hello @Stardlight 
> > I'm still having the same issue. Today will make it the 4th day. Don't know how to rectify this
> 
> @IreneAnyadu kindly tag our mentors so their attention can be called to this 

I created a discussion about this in the issue category yesterday and tagged them but no reply yet.

**Comment by Stardlight** [comment] 2024-03-10 13:12
> > > Hello @Stardlight 
> > > I'm still having the same issue. Today will make it the 4th day. Don't know how to rectify this
> > 
> > @IreneAnyadu kindly tag our mentors so their attention can be called to this 
> 
> I created a discussion about this in the issue category yesterday and tagged them but no reply yet. 

@IreneAnyadu after today if no reply please their attention to it again

**Comment by IreneAnyadu** [comment] 2024-03-10 13:14
> > > > Hello @Stardlight 
> > > > I'm still having the same issue. Today will make it the 4th day. Don't know how to rectify this
> > > 
> > > @IreneAnyadu kindly tag our mentors so their attention can be called to this 
> > 
> > I created a discussion about this in the issue category yesterday and tagged them but no reply yet. 
> 
> @IreneAnyadu after today if no reply please their attention to it again

Yes I'll do that.

**Comment by seanlip** [comment] 2024-03-18 11:41
Duplicate of https://github.com/oppia/oppia/issues/19984 -- let's continue discussion there.

**Closed by seanlip** 2024-03-18 11:41 UTC
