### ISSUE TITLE
Difficulty signing into Oppia website.

### ISSUE THREAD

**Issue by Norrno** [oppia/lessons-team#1099] opened 2024-03-07 13:24 UTC
For over 24 hours now, I have encountered  difficulty submitting and logging in.

**Comment by Ayomiiide** [comment] 2024-03-07 17:14
Hello @Norrno I had this same issue, but when i selected the option that says 'do not send these emails' it worked and signed me in

**Comment by Norrno** [comment] 2024-03-07 17:22
Alright,  let me try again.
Thank you so much.

**Comment by Norrno** [comment] 2024-03-07 17:23
> Hello @Norrno I had this same issue, but when i selected the option that says 'do not send these emails' it worked and signed me in

it worked, thank you soooo much

**Comment by Ayomiiide** [comment] 2024-03-07 17:25
You are welcome

**Comment by Smart3990** [comment] 2024-03-09 01:27
@Ayomide after selecting it you can change that preference at the profile side.

**Comment by seanlip** [comment] 2024-03-18 11:39
This is a known bug, thanks for reporting. Closing as a duplicate of https://github.com/oppia/oppia/issues/19858

**Closed as not planned by seanlip** 2024-03-18 11:39 UTC
